import { computed, ref } from 'vue';
import type { LocalizedFields } from '@/types';

export type Locale = 'en' | 'ru' | 'uk';

const dictionaries: Record<Locale, Record<string, string>> = {
    en: {
        'nav.properties': 'Properties', 'nav.realtors': 'Agents', 'nav.about': 'About', 'nav.contacts': 'Contact', 'nav.compare': 'Compare', 'nav.dashboard': 'Dashboard', 'nav.login': 'Sign in', 'nav.logout': 'Sign out',
        'footer.tagline': 'Property for living, business and investment in the modern city of Nova.', 'footer.navigation': 'Navigation', 'footer.catalog': 'Catalog', 'footer.company': 'Company', 'footer.team': 'Team', 'footer.contact': 'Contact us',
        'home.eyebrow': 'International real estate agency', 'home.title': 'Space for your next chapter', 'home.subtitle': 'Apartments, houses and commercial spaces in the best districts of Nova. We handle negotiations and paperwork.', 'home.searchPlaceholder': 'District, address or property name', 'home.search': 'Find a property', 'home.featured': 'Curated collection', 'home.popular': 'Popular properties', 'home.all': 'View all', 'home.format': 'Choose your format', 'home.formatTitle': 'Property for every goal', 'home.listings': 'listings', 'home.why': 'Why NOVA', 'home.whyTitle': 'Confidence at every step', 'home.whyText': 'We combine local market knowledge, legal expertise and personal service. Every property is reviewed before publication.', 'home.consultation': 'Free consultation', 'home.consultationTitle': 'Tell us what you are looking for', 'home.consultationText': 'We will prepare options and contact you at a convenient time.', 'home.name': 'Your name', 'home.phone': 'Phone', 'home.comment': 'Comment', 'home.send': 'Send request',
        'catalog.eyebrow': 'NOVA collection', 'catalog.title': 'Find your space', 'catalog.subtitle': 'Verified properties for purchase and long-term rent.', 'catalog.filters': 'Filters', 'catalog.reset': 'Reset', 'catalog.search': 'Search', 'catalog.searchPlaceholder': 'Address or property name', 'catalog.operation': 'Deal type', 'catalog.any': 'Any', 'catalog.buy': 'Buy', 'catalog.rent': 'Rent', 'catalog.type': 'Property type', 'catalog.priceFrom': 'Price from', 'catalog.to': 'to', 'catalog.rooms': 'Bedrooms from', 'catalog.area': 'Area from, m²', 'catalog.district': 'District', 'catalog.allDistricts': 'All districts', 'catalog.show': 'Show properties', 'catalog.found': 'Found', 'catalog.newest': 'Newest first', 'catalog.priceAsc': 'Price: low to high', 'catalog.priceDesc': 'Price: high to low', 'catalog.areaDesc': 'Largest first', 'catalog.empty': 'No properties found', 'catalog.emptyText': 'Try changing or resetting the filters.', 'catalog.currency': 'Currency',
        'property.sale': 'For sale', 'property.rent': 'For rent', 'property.month': 'mo.', 'property.rooms': 'beds', 'property.compare': 'Compare', 'property.compared': 'Added to compare', 'property.favorite': 'Save', 'property.saved': 'Saved', 'property.area': 'Area', 'property.floor': 'Floor', 'property.district': 'District', 'property.about': 'About this property', 'property.amenities': 'Amenities', 'property.agent': 'Property agent', 'property.book': 'Book a viewing', 'property.name': 'Name', 'property.phone': 'Phone', 'property.message': 'Message', 'property.send': 'Send request',
        'auth.welcome': 'Welcome back', 'auth.subtitle': 'Sign in to manage favorites, applications and properties.', 'auth.email': 'Email', 'auth.password': 'Password', 'auth.remember': 'Remember me', 'auth.forgot': 'Forgot password?', 'auth.login': 'Sign in', 'auth.noAccount': 'New to NOVA Estate?', 'auth.register': 'Create account', 'auth.backHome': 'Back to home',
        'profile.eyebrow': 'Account settings', 'profile.title': 'Your profile', 'profile.subtitle': 'Keep your contact information current so our team can reach you.', 'profile.info': 'Personal information', 'profile.infoText': 'Update your name, email and contact details.', 'profile.name': 'Full name', 'profile.phone': 'Phone', 'profile.bio': 'About you', 'profile.save': 'Save changes', 'profile.saved': 'Saved', 'profile.security': 'Security', 'profile.passwordText': 'Use a strong, unique password for your NOVA account.', 'profile.currentPassword': 'Current password', 'profile.newPassword': 'New password', 'profile.confirmPassword': 'Confirm new password', 'profile.updatePassword': 'Update password', 'profile.danger': 'Delete account', 'profile.dangerText': 'This permanently deletes the account and all associated data.', 'profile.delete': 'Delete account', 'profile.deleteConfirm': 'Enter your password to confirm account deletion.', 'profile.cancel': 'Cancel',
        'dashboard.overview': 'Overview', 'dashboard.favorites': 'Favorites', 'dashboard.applications': 'Applications', 'dashboard.properties': 'Properties', 'dashboard.users': 'Users', 'dashboard.references': 'Reference data', 'dashboard.profile': 'Profile', 'dashboard.eyebrow': 'Personal workspace', 'dashboard.hello': 'Hello', 'dashboard.newProperty': 'New property', 'dashboard.quickActions': 'Quick actions', 'dashboard.openCatalog': 'Open catalog', 'dashboard.myFavorites': 'My favorites', 'dashboard.checkApplications': 'Check applications', 'pagination.label': 'Pagination', 'pagination.previous': 'Previous', 'pagination.next': 'Next',
        'applications.eyebrow': 'Request history', 'applications.mine': 'My applications', 'applications.clients': 'Client applications', 'applications.filters': 'Filters and sorting', 'applications.search': 'Search', 'applications.searchPlaceholder': 'Client, phone, email or property', 'applications.anyStatus': 'All statuses', 'applications.agent': 'Agent', 'applications.allAgents': 'All agents', 'applications.dateFrom': 'From date', 'applications.dateTo': 'To date', 'applications.sort': 'Sort by', 'applications.newest': 'Newest first', 'applications.oldest': 'Oldest first', 'applications.byStatus': 'By status', 'applications.apply': 'Apply filters', 'applications.reset': 'Reset', 'applications.consultation': 'General consultation', 'applications.unassigned': 'Unassigned', 'applications.empty': 'No applications match these filters.', 'applications.status.new': 'New', 'applications.status.in_progress': 'In progress', 'applications.status.meeting': 'Meeting scheduled', 'applications.status.completed': 'Completed', 'applications.status.cancelled': 'Cancelled',
        'admin.eyebrow': 'Administration', 'admin.users': 'User management', 'admin.usersText': 'Manage roles and account access from one place.', 'admin.total': 'Total users', 'admin.clients': 'Clients', 'admin.agents': 'Agents', 'admin.blocked': 'Blocked', 'admin.user': 'User', 'admin.role': 'Role', 'admin.access': 'Access', 'admin.active': 'Active', 'admin.block': 'Block', 'admin.unblock': 'Unblock', 'admin.search': 'Search by name or email',
        'manage.eyebrow': 'Property management', 'manage.title': 'Your listings', 'manage.subtitle': 'Review publication status, assigned agents and listing performance.', 'manage.add': 'Add property', 'manage.property': 'Property', 'manage.price': 'Price', 'manage.status': 'Status', 'manage.agent': 'Agent', 'manage.unassigned': 'Unassigned', 'manage.edit': 'Edit', 'manage.delete': 'Delete', 'manage.deleteConfirm': 'Delete this property?', 'manage.draft': 'Draft', 'manage.moderation': 'In review', 'manage.published': 'Published', 'manage.sold': 'Sold', 'manage.rented': 'Rented',
        'common.client': 'Client', 'common.realtor': 'Agent', 'common.admin': 'Administrator',
    },
    ru: {
        'nav.properties': 'Недвижимость', 'nav.realtors': 'Риелторы', 'nav.about': 'О компании', 'nav.contacts': 'Контакты', 'nav.compare': 'Сравнение', 'nav.dashboard': 'Кабинет', 'nav.login': 'Войти', 'nav.logout': 'Выйти',
        'footer.tagline': 'Недвижимость для жизни, работы и инвестиций в современном городе Нова.', 'footer.navigation': 'Навигация', 'footer.catalog': 'Каталог', 'footer.company': 'О компании', 'footer.team': 'Команда', 'footer.contact': 'Связаться',
        'home.eyebrow': 'Международное агентство недвижимости', 'home.title': 'Пространство для вашей новой главы', 'home.subtitle': 'Подбираем квартиры, дома и коммерческие объекты в лучших районах города Нова. Берём переговоры и документы на себя.', 'home.searchPlaceholder': 'Район, адрес или название', 'home.search': 'Найти объект', 'home.featured': 'Избранная коллекция', 'home.popular': 'Популярные объекты', 'home.all': 'Весь каталог', 'home.format': 'Выберите формат', 'home.formatTitle': 'Недвижимость под вашу задачу', 'home.listings': 'предложений', 'home.why': 'Почему NOVA', 'home.whyTitle': 'Уверенность на каждом этапе сделки', 'home.whyText': 'Мы объединяем знание локального рынка, юридическую экспертизу и персональный сервис. Каждый объект проходит проверку до публикации.', 'home.consultation': 'Бесплатная консультация', 'home.consultationTitle': 'Расскажите, что вы ищете', 'home.consultationText': 'Подберём варианты и свяжемся с вами в удобное время.', 'home.name': 'Ваше имя', 'home.phone': 'Телефон', 'home.comment': 'Комментарий', 'home.send': 'Отправить заявку',
        'catalog.eyebrow': 'Каталог NOVA', 'catalog.title': 'Найдите своё пространство', 'catalog.subtitle': 'Проверенные объекты для покупки и долгосрочной аренды.', 'catalog.filters': 'Фильтры', 'catalog.reset': 'Сбросить', 'catalog.search': 'Поиск', 'catalog.searchPlaceholder': 'Адрес или название', 'catalog.operation': 'Сделка', 'catalog.any': 'Любая', 'catalog.buy': 'Покупка', 'catalog.rent': 'Аренда', 'catalog.type': 'Тип недвижимости', 'catalog.priceFrom': 'Цена от', 'catalog.to': 'до', 'catalog.rooms': 'Комнат от', 'catalog.area': 'Площадь от, м²', 'catalog.district': 'Район', 'catalog.allDistricts': 'Все районы', 'catalog.show': 'Показать', 'catalog.found': 'Найдено', 'catalog.newest': 'Сначала новые', 'catalog.priceAsc': 'Цена: по возрастанию', 'catalog.priceDesc': 'Цена: по убыванию', 'catalog.areaDesc': 'Сначала просторные', 'catalog.empty': 'Ничего не найдено', 'catalog.emptyText': 'Измените параметры или сбросьте фильтры.', 'catalog.currency': 'Валюта',
        'property.sale': 'Продажа', 'property.rent': 'Аренда', 'property.month': 'мес.', 'property.rooms': 'комн.', 'property.compare': 'Сравнить', 'property.compared': 'Добавлено к сравнению', 'property.favorite': 'Избранное', 'property.saved': 'В избранном', 'property.area': 'Площадь', 'property.floor': 'Этаж', 'property.district': 'Район', 'property.about': 'Об объекте', 'property.amenities': 'Удобства', 'property.agent': 'Ответственный риелтор', 'property.book': 'Записаться на просмотр', 'property.name': 'Имя', 'property.phone': 'Телефон', 'property.message': 'Комментарий', 'property.send': 'Отправить заявку',
        'auth.welcome': 'С возвращением', 'auth.subtitle': 'Войдите, чтобы управлять избранным, заявками и объявлениями.', 'auth.email': 'Email', 'auth.password': 'Пароль', 'auth.remember': 'Запомнить меня', 'auth.forgot': 'Забыли пароль?', 'auth.login': 'Войти', 'auth.noAccount': 'Впервые в NOVA Estate?', 'auth.register': 'Создать аккаунт', 'auth.backHome': 'На главную',
        'profile.eyebrow': 'Настройки аккаунта', 'profile.title': 'Ваш профиль', 'profile.subtitle': 'Поддерживайте контакты актуальными, чтобы наша команда могла связаться с вами.', 'profile.info': 'Личная информация', 'profile.infoText': 'Обновите имя, email и контактные данные.', 'profile.name': 'Имя и фамилия', 'profile.phone': 'Телефон', 'profile.bio': 'О себе', 'profile.save': 'Сохранить', 'profile.saved': 'Сохранено', 'profile.security': 'Безопасность', 'profile.passwordText': 'Используйте надёжный уникальный пароль для аккаунта NOVA.', 'profile.currentPassword': 'Текущий пароль', 'profile.newPassword': 'Новый пароль', 'profile.confirmPassword': 'Подтвердите пароль', 'profile.updatePassword': 'Обновить пароль', 'profile.danger': 'Удаление аккаунта', 'profile.dangerText': 'Аккаунт и связанные данные будут удалены навсегда.', 'profile.delete': 'Удалить аккаунт', 'profile.deleteConfirm': 'Введите пароль, чтобы подтвердить удаление аккаунта.', 'profile.cancel': 'Отмена',
        'dashboard.overview': 'Обзор', 'dashboard.favorites': 'Избранное', 'dashboard.applications': 'Заявки', 'dashboard.properties': 'Объекты', 'dashboard.users': 'Пользователи', 'dashboard.references': 'Справочники', 'dashboard.profile': 'Профиль', 'dashboard.eyebrow': 'Личное пространство', 'dashboard.hello': 'Здравствуйте', 'dashboard.newProperty': 'Новый объект', 'dashboard.quickActions': 'Быстрые действия', 'dashboard.openCatalog': 'Открыть каталог', 'dashboard.myFavorites': 'Моё избранное', 'dashboard.checkApplications': 'Проверить заявки', 'pagination.label': 'Пагинация', 'pagination.previous': 'Назад', 'pagination.next': 'Вперёд',
        'applications.eyebrow': 'История обращений', 'applications.mine': 'Мои заявки', 'applications.clients': 'Заявки клиентов', 'applications.filters': 'Фильтры и сортировка', 'applications.search': 'Поиск', 'applications.searchPlaceholder': 'Клиент, телефон, email или объект', 'applications.anyStatus': 'Все статусы', 'applications.agent': 'Риелтор', 'applications.allAgents': 'Все риелторы', 'applications.dateFrom': 'Дата от', 'applications.dateTo': 'Дата до', 'applications.sort': 'Сортировка', 'applications.newest': 'Сначала новые', 'applications.oldest': 'Сначала старые', 'applications.byStatus': 'По статусу', 'applications.apply': 'Применить', 'applications.reset': 'Сбросить', 'applications.consultation': 'Общая консультация', 'applications.unassigned': 'Не назначен', 'applications.empty': 'По выбранным фильтрам заявок нет.', 'applications.status.new': 'Новая', 'applications.status.in_progress': 'В работе', 'applications.status.meeting': 'Назначена встреча', 'applications.status.completed': 'Завершена', 'applications.status.cancelled': 'Отменена',
        'admin.eyebrow': 'Администрирование', 'admin.users': 'Управление пользователями', 'admin.usersText': 'Роли и доступ к аккаунтам в одном месте.', 'admin.total': 'Всего пользователей', 'admin.clients': 'Клиенты', 'admin.agents': 'Риелторы', 'admin.blocked': 'Заблокированы', 'admin.user': 'Пользователь', 'admin.role': 'Роль', 'admin.access': 'Доступ', 'admin.active': 'Активен', 'admin.block': 'Заблокировать', 'admin.unblock': 'Разблокировать', 'admin.search': 'Поиск по имени или email',
        'manage.eyebrow': 'Управление недвижимостью', 'manage.title': 'Ваши объекты', 'manage.subtitle': 'Контролируйте публикацию, назначенных риелторов и состояние объявлений.', 'manage.add': 'Добавить объект', 'manage.property': 'Объект', 'manage.price': 'Цена', 'manage.status': 'Статус', 'manage.agent': 'Риелтор', 'manage.unassigned': 'Не назначен', 'manage.edit': 'Изменить', 'manage.delete': 'Удалить', 'manage.deleteConfirm': 'Удалить этот объект?', 'manage.draft': 'Черновик', 'manage.moderation': 'На модерации', 'manage.published': 'Опубликован', 'manage.sold': 'Продан', 'manage.rented': 'Сдан',
        'common.client': 'Клиент', 'common.realtor': 'Риелтор', 'common.admin': 'Администратор',
    },
    uk: {
        'nav.properties': 'Нерухомість', 'nav.realtors': 'Рієлтори', 'nav.about': 'Про компанію', 'nav.contacts': 'Контакти', 'nav.compare': 'Порівняння', 'nav.dashboard': 'Кабінет', 'nav.login': 'Увійти', 'nav.logout': 'Вийти',
        'footer.tagline': 'Нерухомість для життя, роботи та інвестицій у сучасному місті Нова.', 'footer.navigation': 'Навігація', 'footer.catalog': 'Каталог', 'footer.company': 'Про компанію', 'footer.team': 'Команда', 'footer.contact': 'Зв’язатися',
        'home.eyebrow': 'Міжнародне агентство нерухомості', 'home.title': 'Простір для вашої нової глави', 'home.subtitle': 'Підбираємо квартири, будинки та комерційні об’єкти в найкращих районах міста Нова. Беремо переговори й документи на себе.', 'home.searchPlaceholder': 'Район, адреса або назва', 'home.search': 'Знайти об’єкт', 'home.featured': 'Обрана колекція', 'home.popular': 'Популярні об’єкти', 'home.all': 'Увесь каталог', 'home.format': 'Оберіть формат', 'home.formatTitle': 'Нерухомість для вашої мети', 'home.listings': 'пропозицій', 'home.why': 'Чому NOVA', 'home.whyTitle': 'Впевненість на кожному етапі угоди', 'home.whyText': 'Ми поєднуємо знання локального ринку, юридичну експертизу та персональний сервіс. Кожен об’єкт проходить перевірку перед публікацією.', 'home.consultation': 'Безкоштовна консультація', 'home.consultationTitle': 'Розкажіть, що ви шукаєте', 'home.consultationText': 'Підберемо варіанти та зв’яжемося з вами у зручний час.', 'home.name': 'Ваше ім’я', 'home.phone': 'Телефон', 'home.comment': 'Коментар', 'home.send': 'Надіслати заявку',
        'catalog.eyebrow': 'Каталог NOVA', 'catalog.title': 'Знайдіть свій простір', 'catalog.subtitle': 'Перевірені об’єкти для купівлі та довгострокової оренди.', 'catalog.filters': 'Фільтри', 'catalog.reset': 'Скинути', 'catalog.search': 'Пошук', 'catalog.searchPlaceholder': 'Адреса або назва', 'catalog.operation': 'Угода', 'catalog.any': 'Будь-яка', 'catalog.buy': 'Купівля', 'catalog.rent': 'Оренда', 'catalog.type': 'Тип нерухомості', 'catalog.priceFrom': 'Ціна від', 'catalog.to': 'до', 'catalog.rooms': 'Кімнат від', 'catalog.area': 'Площа від, м²', 'catalog.district': 'Район', 'catalog.allDistricts': 'Усі райони', 'catalog.show': 'Показати', 'catalog.found': 'Знайдено', 'catalog.newest': 'Спочатку нові', 'catalog.priceAsc': 'Ціна: за зростанням', 'catalog.priceDesc': 'Ціна: за спаданням', 'catalog.areaDesc': 'Спочатку просторі', 'catalog.empty': 'Нічого не знайдено', 'catalog.emptyText': 'Змініть параметри або скиньте фільтри.', 'catalog.currency': 'Валюта',
        'property.sale': 'Продаж', 'property.rent': 'Оренда', 'property.month': 'міс.', 'property.rooms': 'кімн.', 'property.compare': 'Порівняти', 'property.compared': 'Додано до порівняння', 'property.favorite': 'Зберегти', 'property.saved': 'Збережено', 'property.area': 'Площа', 'property.floor': 'Поверх', 'property.district': 'Район', 'property.about': 'Про об’єкт', 'property.amenities': 'Зручності', 'property.agent': 'Відповідальний рієлтор', 'property.book': 'Записатися на перегляд', 'property.name': 'Ім’я', 'property.phone': 'Телефон', 'property.message': 'Коментар', 'property.send': 'Надіслати заявку',
        'auth.welcome': 'З поверненням', 'auth.subtitle': 'Увійдіть, щоб керувати обраним, заявками та оголошеннями.', 'auth.email': 'Email', 'auth.password': 'Пароль', 'auth.remember': 'Запам’ятати мене', 'auth.forgot': 'Забули пароль?', 'auth.login': 'Увійти', 'auth.noAccount': 'Вперше у NOVA Estate?', 'auth.register': 'Створити акаунт', 'auth.backHome': 'На головну',
        'profile.eyebrow': 'Налаштування акаунта', 'profile.title': 'Ваш профіль', 'profile.subtitle': 'Підтримуйте контакти актуальними, щоб наша команда могла зв’язатися з вами.', 'profile.info': 'Особиста інформація', 'profile.infoText': 'Оновіть ім’я, email та контактні дані.', 'profile.name': 'Ім’я та прізвище', 'profile.phone': 'Телефон', 'profile.bio': 'Про себе', 'profile.save': 'Зберегти', 'profile.saved': 'Збережено', 'profile.security': 'Безпека', 'profile.passwordText': 'Використовуйте надійний унікальний пароль для акаунта NOVA.', 'profile.currentPassword': 'Поточний пароль', 'profile.newPassword': 'Новий пароль', 'profile.confirmPassword': 'Підтвердіть пароль', 'profile.updatePassword': 'Оновити пароль', 'profile.danger': 'Видалення акаунта', 'profile.dangerText': 'Акаунт і пов’язані дані буде видалено назавжди.', 'profile.delete': 'Видалити акаунт', 'profile.deleteConfirm': 'Введіть пароль, щоб підтвердити видалення акаунта.', 'profile.cancel': 'Скасувати',
        'dashboard.overview': 'Огляд', 'dashboard.favorites': 'Обране', 'dashboard.applications': 'Заявки', 'dashboard.properties': 'Об’єкти', 'dashboard.users': 'Користувачі', 'dashboard.references': 'Довідники', 'dashboard.profile': 'Профіль', 'dashboard.eyebrow': 'Особистий простір', 'dashboard.hello': 'Вітаємо', 'dashboard.newProperty': 'Новий об’єкт', 'dashboard.quickActions': 'Швидкі дії', 'dashboard.openCatalog': 'Відкрити каталог', 'dashboard.myFavorites': 'Моє обране', 'dashboard.checkApplications': 'Перевірити заявки', 'pagination.label': 'Пагінація', 'pagination.previous': 'Назад', 'pagination.next': 'Далі',
        'applications.eyebrow': 'Історія звернень', 'applications.mine': 'Мої заявки', 'applications.clients': 'Заявки клієнтів', 'applications.filters': 'Фільтри та сортування', 'applications.search': 'Пошук', 'applications.searchPlaceholder': 'Клієнт, телефон, email або об’єкт', 'applications.anyStatus': 'Усі статуси', 'applications.agent': 'Рієлтор', 'applications.allAgents': 'Усі рієлтори', 'applications.dateFrom': 'Дата від', 'applications.dateTo': 'Дата до', 'applications.sort': 'Сортування', 'applications.newest': 'Спочатку нові', 'applications.oldest': 'Спочатку старі', 'applications.byStatus': 'За статусом', 'applications.apply': 'Застосувати', 'applications.reset': 'Скинути', 'applications.consultation': 'Загальна консультація', 'applications.unassigned': 'Не призначений', 'applications.empty': 'За вибраними фільтрами заявок немає.', 'applications.status.new': 'Нова', 'applications.status.in_progress': 'У роботі', 'applications.status.meeting': 'Зустріч призначена', 'applications.status.completed': 'Завершена', 'applications.status.cancelled': 'Скасована',
        'admin.eyebrow': 'Адміністрування', 'admin.users': 'Керування користувачами', 'admin.usersText': 'Ролі та доступ до акаунтів в одному місці.', 'admin.total': 'Усього користувачів', 'admin.clients': 'Клієнти', 'admin.agents': 'Рієлтори', 'admin.blocked': 'Заблоковані', 'admin.user': 'Користувач', 'admin.role': 'Роль', 'admin.access': 'Доступ', 'admin.active': 'Активний', 'admin.block': 'Заблокувати', 'admin.unblock': 'Розблокувати', 'admin.search': 'Пошук за ім’ям або email',
        'manage.eyebrow': 'Керування нерухомістю', 'manage.title': 'Ваші об’єкти', 'manage.subtitle': 'Контролюйте публікацію, призначених рієлторів і стан оголошень.', 'manage.add': 'Додати об’єкт', 'manage.property': 'Об’єкт', 'manage.price': 'Ціна', 'manage.status': 'Статус', 'manage.agent': 'Рієлтор', 'manage.unassigned': 'Не призначений', 'manage.edit': 'Змінити', 'manage.delete': 'Видалити', 'manage.deleteConfirm': 'Видалити цей об’єкт?', 'manage.draft': 'Чернетка', 'manage.moderation': 'На модерації', 'manage.published': 'Опублікований', 'manage.sold': 'Проданий', 'manage.rented': 'Зданий',
        'common.client': 'Клієнт', 'common.realtor': 'Рієлтор', 'common.admin': 'Адміністратор',
    },
};

const initialLocale = typeof window !== 'undefined' && ['en', 'ru', 'uk'].includes(localStorage.getItem('nova_locale') ?? '')
    ? localStorage.getItem('nova_locale') as Locale
    : 'en';
const locale = ref<Locale>(initialLocale);

export function useLocale() {
    const setLocale = (nextLocale: Locale) => {
        locale.value = nextLocale;
        if (typeof window !== 'undefined') {
            localStorage.setItem('nova_locale', nextLocale);
            document.documentElement.lang = nextLocale;
        }
    };
    const t = (key: string) => dictionaries[locale.value][key] ?? dictionaries.en[key] ?? key;
    const localized = (entity: { translations?: LocalizedFields } | null | undefined, field: string, fallback = '') =>
        entity?.translations?.[locale.value]?.[field] ?? entity?.translations?.en?.[field] ?? fallback;

    return { locale: computed(() => locale.value), setLocale, t, localized };
}
