import { computed, ref } from 'vue';
import type { LocalizedFields } from '@/types';

export type Locale = 'en' | 'ru' | 'uk';

const dictionaries: Record<Locale, Record<string, string>> = {
    en: {
        'nav.properties': 'Properties', 'nav.realtors': 'Agents', 'nav.about': 'About', 'nav.contacts': 'Contact', 'nav.compare': 'Compare', 'nav.dashboard': 'Dashboard', 'nav.login': 'Sign in', 'nav.logout': 'Sign out',
        'footer.tagline': 'Property for living, business and investment in the modern city of Nova.', 'footer.navigation': 'Navigation', 'footer.catalog': 'Catalog', 'footer.company': 'Company', 'footer.team': 'Team', 'footer.contact': 'Contact us',
        'home.eyebrow': 'International real estate agency', 'home.title': 'Space for your next chapter', 'home.subtitle': 'Apartments, houses and commercial spaces in the best districts of Nova. We handle negotiations and paperwork.', 'home.searchPlaceholder': 'District, address or property name', 'home.search': 'Find a property', 'home.featured': 'Curated collection', 'home.popular': 'Popular properties', 'home.all': 'View all', 'home.format': 'Choose your format', 'home.formatTitle': 'Property for every goal', 'home.listings': 'listings', 'home.why': 'Why NOVA', 'home.whyTitle': 'Confidence at every step', 'home.whyText': 'We combine local market knowledge, legal expertise and personal service. Every property is reviewed before publication.', 'home.consultation': 'Free consultation', 'home.consultationTitle': 'Tell us what you are looking for', 'home.consultationText': 'We will prepare options and contact you at a convenient time.', 'home.name': 'Your name', 'home.phone': 'Phone', 'home.comment': 'Comment', 'home.send': 'Send request',
        'catalog.eyebrow': 'NOVA collection', 'catalog.title': 'Find your space', 'catalog.subtitle': 'Verified properties for purchase and long-term rent.', 'catalog.filters': 'Filters', 'catalog.reset': 'Reset', 'catalog.search': 'Search', 'catalog.searchPlaceholder': 'Address or property name', 'catalog.operation': 'Deal type', 'catalog.any': 'Any', 'catalog.buy': 'Buy', 'catalog.rent': 'Rent', 'catalog.type': 'Property type', 'catalog.priceFrom': 'Price from', 'catalog.to': 'to', 'catalog.rooms': 'Bedrooms from', 'catalog.area': 'Area from, m²', 'catalog.district': 'District', 'catalog.allDistricts': 'All districts', 'catalog.show': 'Show properties', 'catalog.found': 'Found', 'catalog.newest': 'Newest first', 'catalog.priceAsc': 'Price: low to high', 'catalog.priceDesc': 'Price: high to low', 'catalog.areaDesc': 'Largest first', 'catalog.empty': 'No properties found', 'catalog.emptyText': 'Try changing or resetting the filters.', 'catalog.currency': 'Currency',
        'property.sale': 'For sale', 'property.rent': 'For rent', 'property.month': 'mo.', 'property.rooms': 'beds', 'property.compare': 'Compare', 'property.compared': 'Added to compare', 'property.favorite': 'Save', 'property.saved': 'Saved', 'property.area': 'Area', 'property.floor': 'Floor', 'property.district': 'District', 'property.about': 'About this property', 'property.amenities': 'Amenities', 'property.agent': 'Property agent', 'property.book': 'Book a viewing', 'property.name': 'Name', 'property.phone': 'Phone', 'property.message': 'Message', 'property.send': 'Send request',
        'auth.welcome': 'Welcome back', 'auth.subtitle': 'Sign in to manage favorites, applications and properties.', 'auth.email': 'Email', 'auth.password': 'Password', 'auth.remember': 'Remember me', 'auth.forgot': 'Forgot password?', 'auth.login': 'Sign in', 'auth.noAccount': 'New to NOVA Estate?', 'auth.register': 'Create account', 'auth.backHome': 'Back to home',
        'profile.eyebrow': 'Account settings', 'profile.title': 'Your profile', 'profile.subtitle': 'Keep your contact information current so our team can reach you.', 'profile.info': 'Personal information', 'profile.infoText': 'Update your name, email and contact details.', 'profile.name': 'Full name', 'profile.phone': 'Phone', 'profile.bio': 'About you', 'profile.save': 'Save changes', 'profile.saved': 'Saved', 'profile.security': 'Security', 'profile.passwordText': 'Use a strong, unique password for your NOVA account.', 'profile.currentPassword': 'Current password', 'profile.newPassword': 'New password', 'profile.confirmPassword': 'Confirm new password', 'profile.updatePassword': 'Update password', 'profile.danger': 'Delete account', 'profile.dangerText': 'This permanently deletes the account and all associated data.', 'profile.delete': 'Delete account', 'profile.deleteConfirm': 'Enter your password to confirm account deletion.', 'profile.cancel': 'Cancel',
        'dashboard.overview': 'Overview', 'dashboard.favorites': 'Favorites', 'dashboard.applications': 'Applications', 'dashboard.properties': 'Properties', 'dashboard.users': 'Users', 'dashboard.references': 'Reference data', 'dashboard.profile': 'Profile', 'dashboard.eyebrow': 'Personal workspace', 'dashboard.hello': 'Hello', 'dashboard.newProperty': 'New property', 'dashboard.quickActions': 'Quick actions', 'dashboard.openCatalog': 'Open catalog', 'dashboard.myFavorites': 'My favorites', 'dashboard.checkApplications': 'Check applications', 'pagination.label': 'Pagination', 'pagination.previous': 'Previous', 'pagination.next': 'Next',
        'applications.eyebrow': 'Request history', 'applications.mine': 'My applications', 'applications.clients': 'Client applications', 'applications.filters': 'Filters and sorting', 'applications.search': 'Search', 'applications.searchPlaceholder': 'Client, phone, email or property', 'applications.anyStatus': 'All statuses', 'applications.agent': 'Agent', 'applications.allAgents': 'All agents', 'applications.dateFrom': 'From date', 'applications.dateTo': 'To date', 'applications.sort': 'Sort by', 'applications.newest': 'Newest first', 'applications.oldest': 'Oldest first', 'applications.byStatus': 'By status', 'applications.apply': 'Apply filters', 'applications.reset': 'Reset', 'applications.consultation': 'General consultation', 'applications.unassigned': 'Unassigned', 'applications.empty': 'No applications match these filters.', 'applications.status.new': 'New', 'applications.status.in_progress': 'In progress', 'applications.status.meeting': 'Meeting scheduled', 'applications.status.completed': 'Completed', 'applications.status.cancelled': 'Cancelled',
        'admin.eyebrow': 'Administration', 'admin.users': 'User management', 'admin.usersText': 'Manage roles and account access from one place.', 'admin.total': 'Total users', 'admin.clients': 'Clients', 'admin.agents': 'Agents', 'admin.blocked': 'Blocked', 'admin.user': 'User', 'admin.role': 'Role', 'admin.access': 'Access', 'admin.active': 'Active', 'admin.block': 'Block', 'admin.unblock': 'Unblock', 'admin.search': 'Search by name or email',
        'manage.eyebrow': 'Property management', 'manage.title': 'Your listings', 'manage.subtitle': 'Review publication status, assigned agents and listing performance.', 'manage.add': 'Add property', 'manage.property': 'Property', 'manage.price': 'Price', 'manage.status': 'Status', 'manage.agent': 'Agent', 'manage.unassigned': 'Unassigned', 'manage.edit': 'Edit', 'manage.delete': 'Delete', 'manage.deleteConfirm': 'Delete this property?', 'manage.draft': 'Draft', 'manage.moderation': 'In review', 'manage.published': 'Published', 'manage.sold': 'Sold', 'manage.rented': 'Rented',
        'common.client': 'Client', 'common.realtor': 'Agent', 'common.admin': 'Administrator',
    },
    ru: {
        'nav.properties': 'Недвижимость', 'nav.realtors': 'Риелторы', 'nav.about': 'О компании', 'nav.contacts': 'Контакты', 'nav.compare': 'Сравнение', 'nav.dashboard': 'Кабинет', 'nav.login': 'Войти', 'nav.logout': 'Выйти',
        'footer.tagline': 'Недвижимость для жизни, работы и инвестиций в современном городе Нова.', 'footer.navigation': 'Навигация', 'footer.catalog': 'Каталог', 'footer.company': 'О компании', 'footer.team': 'Команда', 'footer.contact': 'Связаться',
        'home.eyebrow': 'Международное агентство недвижимости', 'home.title': 'Пространство для вашей новой главы', 'home.subtitle': 'Подбираем квартиры, дома и коммерческие объекты в лучших районах города Нова. Берём переговоры и документы на себя.', 'home.searchPlaceholder': 'Район, адрес или название', 'home.search': 'Найти объект', 'home.featured': 'Избранная коллекция', 'home.popular': 'Популярные объекты', 'home.all': 'Весь каталог', 'home.format': 'Выберите формат', 'home.formatTitle': 'Недвижимость под вашу задачу', 'home.listings': 'предложений', 'home.why': 'Почему NOVA', 'home.whyTitle': 'Уверенность на каждом этапе сделки', 'home.whyText': 'Мы объединяем знание локального рынка, юридическую экспертизу и персональный сервис. Каждый объект проходит проверку до публикации.', 'home.consultation': 'Бесплатная консультация', 'home.consultationTitle': 'Расскажите, что вы ищете', 'home.consultationText': 'Подберём варианты и свяжемся с вами в удобное время.', 'home.name': 'Ваше имя', 'home.phone': 'Телефон', 'home.comment': 'Комментарий', 'home.send': 'Отправить заявку',
        'catalog.eyebrow': 'Каталог NOVA', 'catalog.title': 'Найдите своё пространство', 'catalog.subtitle': 'Проверенные объекты для покупки и долгосрочной аренды.', 'catalog.filters': 'Фильтры', 'catalog.reset': 'Сбросить', 'catalog.search': 'Поиск', 'catalog.searchPlaceholder': 'Адрес или название', 'catalog.operation': 'Сделка', 'catalog.any': 'Любая', 'catalog.buy': 'Покупка', 'catalog.rent': 'Аренда', 'catalog.type': 'Тип недвижимости', 'catalog.priceFrom': 'Цена от', 'catalog.to': 'до', 'catalog.rooms': 'Комнат от', 'catalog.area': 'Площадь от, м²', 'catalog.district': 'Район', 'catalog.allDistricts': 'Все районы', 'catalog.show': 'Показать', 'catalog.found': 'Найдено', 'catalog.newest': 'Сначала новые', 'catalog.priceAsc': 'Цена: по возрастанию', 'catalog.priceDesc': 'Цена: по убыванию', 'catalog.areaDesc': 'Сначала просторные', 'catalog.empty': 'Ничего не найдено', 'catalog.emptyText': 'Измените параметры или сбросьте фильтры.', 'catalog.currency': 'Валюта',
        'property.sale': 'Продажа', 'property.rent': 'Аренда', 'property.month': 'мес.', 'property.rooms': 'комн.', 'property.compare': 'Сравнить', 'property.compared': 'Добавлено к сравнению', 'property.favorite': 'Избранное', 'property.saved': 'В избранном', 'property.area': 'Площадь', 'property.floor': 'Этаж', 'property.district': 'Район', 'property.about': 'Об объекте', 'property.amenities': 'Удобства', 'property.agent': 'Ответственный риелтор', 'property.book': 'Записаться на просмотр', 'property.name': 'Имя', 'property.phone': 'Телефон', 'property.message': 'Комментарий', 'property.send': 'Отправить заявку',
        'auth.welcome': 'С возвращением', 'auth.subtitle': 'Войдите, чтобы управлять избранным, заявками и объявлениями.', 'auth.email': 'Email', 'auth.password': 'Пароль', 'auth.remember': 'Запомнить меня', 'auth.forgot': 'Забыли пароль?', 'auth.login': 'Войти', 'auth.noAccount': 'Впервые в NOVA Estate?', 'auth.register': 'Создать аккаунт', 'auth.backHome': 'На главную',
        'profile.eyebrow': 'Настройки аккаунта', 'profile.title': 'Ваш профиль', 'profile.subtitle': 'Поддерживайте контакты актуальными, чтобы наша команда могла связаться с вами.', 'profile.info': 'Личная информация', 'profile.infoText': 'Обновите имя, email и контактные данные.', 'profile.name': 'Имя и фамилия', 'profile.phone': 'Телефон', 'profile.bio': 'О себе', 'profile.save': 'Сохранить', 'profile.saved': 'Сохранено', 'profile.security': 'Безопасность', 'profile.passwordText': 'Используйте надёжный уникальный пароль для аккаунта NOVA.', 'profile.currentPassword': 'Текущий пароль', 'profile.newPassword': 'Новый пароль', 'profile.confirmPassword': 'Подтвердите пароль', 'profile.updatePassword': 'Обновить пароль', 'profile.danger': 'Удаление аккаунта', 'profile.dangerText': 'Аккаунт и связанные данные будут удалены навсегда.', 'profile.delete': 'Удалить аккаунт', 'profile.deleteConfirm': 'Введите пароль, чтобы подтвердить удаление аккаунта.', 'profile.cancel': 'Отмена',
        'dashboard.overview': 'Обзор', 'dashboard.favorites': 'Избранное', 'dashboard.applications': 'Заявки', 'dashboard.properties': 'Объекты', 'dashboard.users': 'Пользователи', 'dashboard.references': 'Справочники', 'dashboard.profile': 'Профиль', 'dashboard.eyebrow': 'Личное пространство', 'dashboard.hello': 'Здравствуйте', 'dashboard.newProperty': 'Новый объект', 'dashboard.quickActions': 'Быстрые действия', 'dashboard.openCatalog': 'Открыть каталог', 'dashboard.myFavorites': 'Моё избранное', 'dashboard.checkApplications': 'Проверить заявки', 'pagination.label': 'Пагинация', 'pagination.previous': 'Назад', 'pagination.next': 'Вперёд',
        'applications.eyebrow': 'История обращений', 'applications.mine': 'Мои заявки', 'applications.clients': 'Заявки клиентов', 'applications.filters': 'Фильтры и сортировка', 'applications.search': 'Поиск', 'applications.searchPlaceholder': 'Клиент, телефон, email или объект', 'applications.anyStatus': 'Все статусы', 'applications.agent': 'Риелтор', 'applications.allAgents': 'Все риелторы', 'applications.dateFrom': 'Дата от', 'applications.dateTo': 'Дата до', 'applications.sort': 'Сортировка', 'applications.newest': 'Сначала новые', 'applications.oldest': 'Сначала старые', 'applications.byStatus': 'По статусу', 'applications.apply': 'Применить', 'applications.reset': 'Сбросить', 'applications.consultation': 'Общая консультация', 'applications.unassigned': 'Не назначен', 'applications.empty': 'По выбранным фильтрам заявок нет.', 'applications.status.new': 'Новая', 'applications.status.in_progress': 'В работе', 'applications.status.meeting': 'Назначена встреча', 'applications.status.completed': 'Завершена', 'applications.status.cancelled': 'Отменена',
        'admin.eyebrow': 'Администрирование', 'admin.users': 'Управление пользователями', 'admin.usersText': 'Роли и доступ к аккаунтам в одном месте.', 'admin.total': 'Всего пользователей', 'admin.clients': 'Клиенты', 'admin.agents': 'Риелторы', 'admin.blocked': 'Заблокированы', 'admin.user': 'Пользователь', 'admin.role': 'Роль', 'admin.access': 'Доступ', 'admin.active': 'Активен', 'admin.block': 'Заблокировать', 'admin.unblock': 'Разблокировать', 'admin.search': 'Поиск по имени или email',
        'manage.eyebrow': 'Управление недвижимостью', 'manage.title': 'Ваши объекты', 'manage.subtitle': 'Контролируйте публикацию, назначенных риелторов и состояние объявлений.', 'manage.add': 'Добавить объект', 'manage.property': 'Объект', 'manage.price': 'Цена', 'manage.status': 'Статус', 'manage.agent': 'Риелтор', 'manage.unassigned': 'Не назначен', 'manage.edit': 'Изменить', 'manage.delete': 'Удалить', 'manage.deleteConfirm': 'Удалить этот объект?', 'manage.draft': 'Черновик', 'manage.moderation': 'На модерации', 'manage.published': 'Опубликован', 'manage.sold': 'Продан', 'manage.rented': 'Сдан',
        'common.client': 'Клиент', 'common.realtor': 'Риелтор', 'common.admin': 'Администратор',
    },
    uk: {
        'nav.properties': 'Нерухомість', 'nav.realtors': 'Рієлтори', 'nav.about': 'Про компанію', 'nav.contacts': 'Контакти', 'nav.compare': 'Порівняння', 'nav.dashboard': 'Кабінет', 'nav.login': 'Увійти', 'nav.logout': 'Вийти',
        'footer.tagline': 'Нерухомість для життя, роботи та інвестицій у сучасному місті Нова.', 'footer.navigation': 'Навігація', 'footer.catalog': 'Каталог', 'footer.company': 'Про компанію', 'footer.team': 'Команда', 'footer.contact': 'Зв’язатися',
        'home.eyebrow': 'Міжнародне агентство нерухомості', 'home.title': 'Простір для вашої нової глави', 'home.subtitle': 'Підбираємо квартири, будинки та комерційні об’єкти в найкращих районах міста Нова. Беремо переговори й документи на себе.', 'home.searchPlaceholder': 'Район, адреса або назва', 'home.search': 'Знайти об’єкт', 'home.featured': 'Обрана колекція', 'home.popular': 'Популярні об’єкти', 'home.all': 'Увесь каталог', 'home.format': 'Оберіть формат', 'home.formatTitle': 'Нерухомість для вашої мети', 'home.listings': 'пропозицій', 'home.why': 'Чому NOVA', 'home.whyTitle': 'Впевненість на кожному етапі угоди', 'home.whyText': 'Ми поєднуємо знання локального ринку, юридичну експертизу та персональний сервіс. Кожен об’єкт проходить перевірку перед публікацією.', 'home.consultation': 'Безкоштовна консультація', 'home.consultationTitle': 'Розкажіть, що ви шукаєте', 'home.consultationText': 'Підберемо варіанти та зв’яжемося з вами у зручний час.', 'home.name': 'Ваше ім’я', 'home.phone': 'Телефон', 'home.comment': 'Коментар', 'home.send': 'Надіслати заявку',
        'catalog.eyebrow': 'Каталог NOVA', 'catalog.title': 'Знайдіть свій простір', 'catalog.subtitle': 'Перевірені об’єкти для купівлі та довгострокової оренди.', 'catalog.filters': 'Фільтри', 'catalog.reset': 'Скинути', 'catalog.search': 'Пошук', 'catalog.searchPlaceholder': 'Адреса або назва', 'catalog.operation': 'Угода', 'catalog.any': 'Будь-яка', 'catalog.buy': 'Купівля', 'catalog.rent': 'Оренда', 'catalog.type': 'Тип нерухомості', 'catalog.priceFrom': 'Ціна від', 'catalog.to': 'до', 'catalog.rooms': 'Кімнат від', 'catalog.area': 'Площа від, м²', 'catalog.district': 'Район', 'catalog.allDistricts': 'Усі райони', 'catalog.show': 'Показати', 'catalog.found': 'Знайдено', 'catalog.newest': 'Спочатку нові', 'catalog.priceAsc': 'Ціна: за зростанням', 'catalog.priceDesc': 'Ціна: за спаданням', 'catalog.areaDesc': 'Спочатку просторі', 'catalog.empty': 'Нічого не знайдено', 'catalog.emptyText': 'Змініть параметри або скиньте фільтри.', 'catalog.currency': 'Валюта',
        'property.sale': 'Продаж', 'property.rent': 'Оренда', 'property.month': 'міс.', 'property.rooms': 'кімн.', 'property.compare': 'Порівняти', 'property.compared': 'Додано до порівняння', 'property.favorite': 'Зберегти', 'property.saved': 'Збережено', 'property.area': 'Площа', 'property.floor': 'Поверх', 'property.district': 'Район', 'property.about': 'Про об’єкт', 'property.amenities': 'Зручності', 'property.agent': 'Відповідальний рієлтор', 'property.book': 'Записатися на перегляд', 'property.name': 'Ім’я', 'property.phone': 'Телефон', 'property.message': 'Коментар', 'property.send': 'Надіслати заявку',
        'auth.welcome': 'З поверненням', 'auth.subtitle': 'Увійдіть, щоб керувати обраним, заявками та оголошеннями.', 'auth.email': 'Email', 'auth.password': 'Пароль', 'auth.remember': 'Запам’ятати мене', 'auth.forgot': 'Забули пароль?', 'auth.login': 'Увійти', 'auth.noAccount': 'Вперше у NOVA Estate?', 'auth.register': 'Створити акаунт', 'auth.backHome': 'На головну',
        'profile.eyebrow': 'Налаштування акаунта', 'profile.title': 'Ваш профіль', 'profile.subtitle': 'Підтримуйте контакти актуальними, щоб наша команда могла зв’язатися з вами.', 'profile.info': 'Особиста інформація', 'profile.infoText': 'Оновіть ім’я, email та контактні дані.', 'profile.name': 'Ім’я та прізвище', 'profile.phone': 'Телефон', 'profile.bio': 'Про себе', 'profile.save': 'Зберегти', 'profile.saved': 'Збережено', 'profile.security': 'Безпека', 'profile.passwordText': 'Використовуйте надійний унікальний пароль для акаунта NOVA.', 'profile.currentPassword': 'Поточний пароль', 'profile.newPassword': 'Новий пароль', 'profile.confirmPassword': 'Підтвердіть пароль', 'profile.updatePassword': 'Оновити пароль', 'profile.danger': 'Видалення акаунта', 'profile.dangerText': 'Акаунт і пов’язані дані буде видалено назавжди.', 'profile.delete': 'Видалити акаунт', 'profile.deleteConfirm': 'Введіть пароль, щоб підтвердити видалення акаунта.', 'profile.cancel': 'Скасувати',
        'dashboard.overview': 'Огляд', 'dashboard.favorites': 'Обране', 'dashboard.applications': 'Заявки', 'dashboard.properties': 'Об’єкти', 'dashboard.users': 'Користувачі', 'dashboard.references': 'Довідники', 'dashboard.profile': 'Профіль', 'dashboard.eyebrow': 'Особистий простір', 'dashboard.hello': 'Вітаємо', 'dashboard.newProperty': 'Новий об’єкт', 'dashboard.quickActions': 'Швидкі дії', 'dashboard.openCatalog': 'Відкрити каталог', 'dashboard.myFavorites': 'Моє обране', 'dashboard.checkApplications': 'Перевірити заявки', 'pagination.label': 'Пагінація', 'pagination.previous': 'Назад', 'pagination.next': 'Далі',
        'applications.eyebrow': 'Історія звернень', 'applications.mine': 'Мої заявки', 'applications.clients': 'Заявки клієнтів', 'applications.filters': 'Фільтри та сортування', 'applications.search': 'Пошук', 'applications.searchPlaceholder': 'Клієнт, телефон, email або об’єкт', 'applications.anyStatus': 'Усі статуси', 'applications.agent': 'Рієлтор', 'applications.allAgents': 'Усі рієлтори', 'applications.dateFrom': 'Дата від', 'applications.dateTo': 'Дата до', 'applications.sort': 'Сортування', 'applications.newest': 'Спочатку нові', 'applications.oldest': 'Спочатку старі', 'applications.byStatus': 'За статусом', 'applications.apply': 'Застосувати', 'applications.reset': 'Скинути', 'applications.consultation': 'Загальна консультація', 'applications.unassigned': 'Не призначений', 'applications.empty': 'За вибраними фільтрами заявок немає.', 'applications.status.new': 'Нова', 'applications.status.in_progress': 'У роботі', 'applications.status.meeting': 'Зустріч призначена', 'applications.status.completed': 'Завершена', 'applications.status.cancelled': 'Скасована',
        'admin.eyebrow': 'Адміністрування', 'admin.users': 'Керування користувачами', 'admin.usersText': 'Ролі та доступ до акаунтів в одному місці.', 'admin.total': 'Усього користувачів', 'admin.clients': 'Клієнти', 'admin.agents': 'Рієлтори', 'admin.blocked': 'Заблоковані', 'admin.user': 'Користувач', 'admin.role': 'Роль', 'admin.access': 'Доступ', 'admin.active': 'Активний', 'admin.block': 'Заблокувати', 'admin.unblock': 'Розблокувати', 'admin.search': 'Пошук за ім’ям або email',
        'manage.eyebrow': 'Керування нерухомістю', 'manage.title': 'Ваші об’єкти', 'manage.subtitle': 'Контролюйте публікацію, призначених рієлторів і стан оголошень.', 'manage.add': 'Додати об’єкт', 'manage.property': 'Об’єкт', 'manage.price': 'Ціна', 'manage.status': 'Статус', 'manage.agent': 'Рієлтор', 'manage.unassigned': 'Не призначений', 'manage.edit': 'Змінити', 'manage.delete': 'Видалити', 'manage.deleteConfirm': 'Видалити цей об’єкт?', 'manage.draft': 'Чернетка', 'manage.moderation': 'На модерації', 'manage.published': 'Опублікований', 'manage.sold': 'Проданий', 'manage.rented': 'Зданий',
        'common.client': 'Клієнт', 'common.realtor': 'Рієлтор', 'common.admin': 'Адміністратор',
    },
};

Object.assign(dictionaries.en, {
    'Заявка отправлена. Риелтор свяжется с вами.': 'Request sent. An agent will contact you.', 'Статус заявки обновлён.': 'Request status updated.', 'Объект создан.': 'Property created.', 'Объект обновлён.': 'Property updated.', 'Объект удалён.': 'Property deleted.', 'Фотография удалена.': 'Photo deleted.', 'Пользователь обновлён.': 'User updated.', 'Тип недвижимости добавлен.': 'Property type added.', 'Тип недвижимости удалён.': 'Property type deleted.', 'Удобство добавлено.': 'Amenity added.', 'Удобство удалено.': 'Amenity deleted.', 'Объект добавлен в избранное.': 'Property saved.', 'Объект удалён из избранного.': 'Property removed from favorites.', 'Спасибо! Мы свяжемся с вами в ближайшее время.': 'Thank you! We will contact you soon.',
    'form.editTitle': 'Edit property', 'form.newTitle': 'New property', 'form.back': 'Back', 'form.basic': 'Basic information', 'form.title': 'Title', 'form.description': 'Description', 'form.select': 'Select', 'form.price': 'Price, $', 'form.location': 'Location and details', 'form.address': 'Address', 'form.totalFloors': 'Total floors', 'form.publication': 'Publication and photos', 'form.featured': 'Featured property', 'form.addPhotos': 'Add photos (up to 10)', 'form.save': 'Save changes', 'form.create': 'Create property',
    'references.types': 'Property types', 'references.amenities': 'Amenities', 'references.typeName': 'Type name', 'references.amenityName': 'Amenity name', 'references.typeExample': 'For example, apartment', 'references.amenityExample': 'For example, pool', 'references.add': 'Add', 'references.deleteConfirm': 'Delete this entry?', 'references.properties': 'properties',
    'about.hero': 'We find more than square metres. We find a place to live.', 'about.intro': 'An international agency in Nova with local expertise and a transparent approach to every transaction.', 'about.trust': 'An agency you can trust', 'about.history': 'Since 2014, we have guided buyers, renters and investors. Our team checks property histories, negotiates terms and stays close after the keys are handed over.', 'about.platform': 'NOVA Estate brings verified listings, personal guidance and transparent request management into one digital platform.', 'about.deals': 'transactions', 'about.years': 'years of experience', 'about.referred': 'through referrals', 'about.districts': 'city districts', 'about.ready': 'Ready to start your search?', 'about.ctaText': 'Browse current listings or speak with an expert.',
    'contacts.eyebrow': 'Stay in touch', 'contacts.intro': 'Tell us what you need. We reply within one working hour.', 'contacts.office': 'Office', 'contacts.address': 'Nova, Mira Avenue, 18', 'contacts.hours': 'Opening hours', 'contacts.schedule': 'Mon–Sat, 09:00–20:00', 'contacts.subject': 'Subject', 'contacts.send': 'Send message',
    'realtors.team': 'NOVA team', 'realtors.hero': 'Experts who listen', 'realtors.intro': 'Your personal agent guides you from the first consultation to the handover of keys.', 'realtors.properties': 'active listings', 'realtors.consultation': 'Request a consultation', 'realtors.bio.alina@nova.test': 'Residential property and family relocation specialist.', 'realtors.bio.mark@nova.test': 'Investment and commercial property specialist.', 'realtors.bio.sofia@nova.test': 'Helping clients find homes and long-term rentals.',
    'realtors.name.alina@nova.test': 'Alina Vetrova', 'realtors.name.mark@nova.test': 'Mark Levin', 'realtors.name.sofia@nova.test': 'Sofia Ray',
    'property.similarEyebrow': 'Similar properties', 'property.similarTitle': 'You may also like', 'property.viewingMessage': 'I would like to arrange a viewing.',
    'favorites.eyebrow': 'Saved properties', 'favorites.empty': 'No saved properties yet',
    'compare.eyebrow': 'Up to four properties', 'compare.title': 'Compare properties', 'compare.empty': 'Your comparison is empty', 'compare.emptyText': 'Add properties from the catalog to see the differences.', 'compare.openCatalog': 'Go to catalog', 'compare.feature': 'Feature', 'compare.remove': 'Remove', 'compare.price': 'Price', 'compare.operation': 'Deal type',
    'error.403.title': 'Access denied', 'error.403.text': 'Your account does not have permission to view this page.', 'error.404.title': 'Page not found', 'error.404.text': 'The address may have changed or the page may have been removed.', 'error.500.title': 'Something went wrong', 'error.500.text': 'Please try refreshing the page in a little while.', 'error.title': 'Error', 'error.text': 'The request could not be completed.',
    'stats.users': 'Users', 'stats.properties': 'Properties', 'stats.moderation': 'In review', 'stats.applications': 'Applications', 'stats.myProperties': 'My properties', 'stats.published': 'Published', 'stats.newApplications': 'New applications', 'stats.completed': 'Completed', 'stats.favorites': 'Favorites', 'stats.myApplications': 'My applications', 'stats.inProgress': 'In progress',
});
Object.assign(dictionaries.ru, {
    'form.editTitle': 'Редактирование объекта', 'form.newTitle': 'Новый объект', 'form.back': 'Назад', 'form.basic': 'Основная информация', 'form.title': 'Название', 'form.description': 'Описание', 'form.select': 'Выберите', 'form.price': 'Цена, $', 'form.location': 'Расположение и параметры', 'form.address': 'Адрес', 'form.totalFloors': 'Этажей всего', 'form.publication': 'Публикация и фотографии', 'form.featured': 'Рекомендуемый объект', 'form.addPhotos': 'Добавить фотографии (до 10)', 'form.save': 'Сохранить', 'form.create': 'Создать объект',
    'references.types': 'Типы недвижимости', 'references.amenities': 'Удобства', 'references.typeName': 'Название типа', 'references.amenityName': 'Название удобства', 'references.typeExample': 'Например, апартаменты', 'references.amenityExample': 'Например, бассейн', 'references.add': 'Добавить', 'references.deleteConfirm': 'Удалить запись?', 'references.properties': 'объектов',
    'about.hero': 'Находим не квадратные метры, а место для жизни', 'about.intro': 'Международное агентство в городе Нова с локальной экспертизой и прозрачным подходом к каждой сделке.', 'about.trust': 'Агентство, которому доверяют', 'about.history': 'С 2014 года мы сопровождаем покупателей, арендаторов и инвесторов. Команда проверяет юридическую историю объектов, ведёт переговоры и остаётся рядом после передачи ключей.', 'about.platform': 'Единая цифровая платформа NOVA Estate объединяет каталог проверенных объектов, персональное сопровождение клиентов и прозрачное управление заявками.', 'about.deals': 'сделок', 'about.years': 'лет опыта', 'about.referred': 'по рекомендации', 'about.districts': 'районов города', 'about.ready': 'Готовы начать поиск?', 'about.ctaText': 'Посмотрите актуальные предложения или поговорите с экспертом.',
    'contacts.eyebrow': 'Будем на связи', 'contacts.intro': 'Расскажите о вашей задаче. Ответим в рабочее время в течение одного часа.', 'contacts.office': 'Офис', 'contacts.address': 'Нова, Авеню Мира, 18', 'contacts.hours': 'Часы работы', 'contacts.schedule': 'Пн–Сб, 09:00–20:00', 'contacts.subject': 'Тема', 'contacts.send': 'Отправить сообщение',
    'realtors.team': 'Команда NOVA', 'realtors.hero': 'Эксперты, которые слушают', 'realtors.intro': 'Персональный риелтор сопровождает вас от первой консультации до передачи ключей.', 'realtors.properties': 'объектов в работе', 'realtors.consultation': 'Получить консультацию', 'realtors.bio.alina@nova.test': 'Эксперт по жилой недвижимости и семейным переездам.', 'realtors.bio.mark@nova.test': 'Специалист по инвестициям и коммерческим объектам.', 'realtors.bio.sofia@nova.test': 'Помогает найти недвижимость для жизни и долгосрочной аренды.',
    'realtors.name.alina@nova.test': 'Алина Ветрова', 'realtors.name.mark@nova.test': 'Марк Левин', 'realtors.name.sofia@nova.test': 'София Рэй',
    'property.similarEyebrow': 'Похожие предложения', 'property.similarTitle': 'Вам может подойти', 'property.viewingMessage': 'Хочу договориться о просмотре объекта.',
    'favorites.eyebrow': 'Сохранённые варианты', 'favorites.empty': 'Пока ничего не сохранено',
    'compare.eyebrow': 'До четырёх объектов', 'compare.title': 'Сравнение объектов', 'compare.empty': 'Список сравнения пуст', 'compare.emptyText': 'Добавьте объекты из каталога, чтобы увидеть различия.', 'compare.openCatalog': 'Перейти в каталог', 'compare.feature': 'Характеристика', 'compare.remove': 'Убрать', 'compare.price': 'Цена', 'compare.operation': 'Тип сделки',
    'error.403.title': 'Доступ запрещён', 'error.403.text': 'У вашей учётной записи нет прав для просмотра этой страницы.', 'error.404.title': 'Страница не найдена', 'error.404.text': 'Возможно, адрес изменился или страница была удалена.', 'error.500.title': 'Что-то пошло не так', 'error.500.text': 'Попробуйте обновить страницу немного позже.', 'error.title': 'Ошибка', 'error.text': 'Не удалось выполнить запрос.',
    'stats.users': 'Пользователи', 'stats.properties': 'Объекты', 'stats.moderation': 'На модерации', 'stats.applications': 'Заявки', 'stats.myProperties': 'Мои объекты', 'stats.published': 'Опубликовано', 'stats.newApplications': 'Новые заявки', 'stats.completed': 'Завершено', 'stats.favorites': 'Избранное', 'stats.myApplications': 'Мои заявки', 'stats.inProgress': 'В работе',
});
Object.assign(dictionaries.uk, {
    'Заявка отправлена. Риелтор свяжется с вами.': 'Заявку надіслано. Рієлтор зв’яжеться з вами.', 'Статус заявки обновлён.': 'Статус заявки оновлено.', 'Объект создан.': 'Об’єкт створено.', 'Объект обновлён.': 'Об’єкт оновлено.', 'Объект удалён.': 'Об’єкт видалено.', 'Фотография удалена.': 'Фотографію видалено.', 'Пользователь обновлён.': 'Користувача оновлено.', 'Тип недвижимости добавлен.': 'Тип нерухомості додано.', 'Тип недвижимости удалён.': 'Тип нерухомості видалено.', 'Удобство добавлено.': 'Зручність додано.', 'Удобство удалено.': 'Зручність видалено.', 'Объект добавлен в избранное.': 'Об’єкт додано до обраного.', 'Объект удалён из избранного.': 'Об’єкт вилучено з обраного.', 'Спасибо! Мы свяжемся с вами в ближайшее время.': 'Дякуємо! Ми зв’яжемося з вами найближчим часом.',
    'form.editTitle': 'Редагування об’єкта', 'form.newTitle': 'Новий об’єкт', 'form.back': 'Назад', 'form.basic': 'Основна інформація', 'form.title': 'Назва', 'form.description': 'Опис', 'form.select': 'Оберіть', 'form.price': 'Ціна, $', 'form.location': 'Розташування й параметри', 'form.address': 'Адреса', 'form.totalFloors': 'Поверхів усього', 'form.publication': 'Публікація та фотографії', 'form.featured': 'Рекомендований об’єкт', 'form.addPhotos': 'Додати фотографії (до 10)', 'form.save': 'Зберегти', 'form.create': 'Створити об’єкт',
    'references.types': 'Типи нерухомості', 'references.amenities': 'Зручності', 'references.typeName': 'Назва типу', 'references.amenityName': 'Назва зручності', 'references.typeExample': 'Наприклад, апартаменти', 'references.amenityExample': 'Наприклад, басейн', 'references.add': 'Додати', 'references.deleteConfirm': 'Видалити запис?', 'references.properties': 'об’єктів',
    'about.hero': 'Знаходимо не квадратні метри, а місце для життя', 'about.intro': 'Міжнародне агентство в місті Нова з місцевою експертизою та прозорим підходом до кожної угоди.', 'about.trust': 'Агентство, якому довіряють', 'about.history': 'З 2014 року ми супроводжуємо покупців, орендарів та інвесторів. Команда перевіряє історію об’єктів, веде переговори й залишається поруч після передачі ключів.', 'about.platform': 'Цифрова платформа NOVA Estate об’єднує каталог перевірених об’єктів, персональний супровід клієнтів і прозоре керування заявками.', 'about.deals': 'угод', 'about.years': 'років досвіду', 'about.referred': 'за рекомендацією', 'about.districts': 'районів міста', 'about.ready': 'Готові розпочати пошук?', 'about.ctaText': 'Перегляньте актуальні пропозиції або поговоріть з експертом.',
    'contacts.eyebrow': 'Будьмо на зв’язку', 'contacts.intro': 'Розкажіть про своє завдання. Відповімо протягом однієї робочої години.', 'contacts.office': 'Офіс', 'contacts.address': 'Нова, проспект Миру, 18', 'contacts.hours': 'Години роботи', 'contacts.schedule': 'Пн–Сб, 09:00–20:00', 'contacts.subject': 'Тема', 'contacts.send': 'Надіслати повідомлення',
    'realtors.team': 'Команда NOVA', 'realtors.hero': 'Експерти, які вміють слухати', 'realtors.intro': 'Персональний рієлтор супроводжує вас від першої консультації до передачі ключів.', 'realtors.properties': 'об’єктів у роботі', 'realtors.consultation': 'Отримати консультацію', 'realtors.bio.alina@nova.test': 'Експертка з житлової нерухомості та сімейних переїздів.', 'realtors.bio.mark@nova.test': 'Фахівець з інвестицій і комерційної нерухомості.', 'realtors.bio.sofia@nova.test': 'Допомагає знайти житло для життя й довгострокової оренди.',
    'realtors.name.alina@nova.test': 'Аліна Вєтрова', 'realtors.name.mark@nova.test': 'Марк Левін', 'realtors.name.sofia@nova.test': 'Софія Рей',
    'property.similarEyebrow': 'Схожі пропозиції', 'property.similarTitle': 'Вам може сподобатися', 'property.viewingMessage': 'Хочу домовитися про перегляд об’єкта.',
    'favorites.eyebrow': 'Збережені варіанти', 'favorites.empty': 'Поки нічого не збережено',
    'compare.eyebrow': 'До чотирьох об’єктів', 'compare.title': 'Порівняння об’єктів', 'compare.empty': 'Список порівняння порожній', 'compare.emptyText': 'Додайте об’єкти з каталогу, щоб побачити відмінності.', 'compare.openCatalog': 'Перейти до каталогу', 'compare.feature': 'Характеристика', 'compare.remove': 'Прибрати', 'compare.price': 'Ціна', 'compare.operation': 'Тип угоди',
    'error.403.title': 'Доступ заборонено', 'error.403.text': 'Ваш обліковий запис не має права переглядати цю сторінку.', 'error.404.title': 'Сторінку не знайдено', 'error.404.text': 'Можливо, адресу змінено або сторінку видалено.', 'error.500.title': 'Щось пішло не так', 'error.500.text': 'Спробуйте оновити сторінку трохи пізніше.', 'error.title': 'Помилка', 'error.text': 'Не вдалося виконати запит.',
    'stats.users': 'Користувачі', 'stats.properties': 'Об’єкти', 'stats.moderation': 'На модерації', 'stats.applications': 'Заявки', 'stats.myProperties': 'Мої об’єкти', 'stats.published': 'Опубліковано', 'stats.newApplications': 'Нові заявки', 'stats.completed': 'Завершено', 'stats.favorites': 'Обране', 'stats.myApplications': 'Мої заявки', 'stats.inProgress': 'У роботі',
});

Object.assign(dictionaries.en, {
    'home.years': 'years of expertise', 'home.deals': 'closed deals', 'home.rating': 'client rating', 'home.support': 'support', 'home.experts': 'NOVA Estate experts',
});
Object.assign(dictionaries.ru, {
    'home.years': 'лет опыта', 'home.deals': 'закрытых сделок', 'home.rating': 'оценка клиентов', 'home.support': 'поддержка', 'home.experts': 'Эксперты NOVA Estate',
});
Object.assign(dictionaries.uk, {
    'home.years': 'років досвіду', 'home.deals': 'завершених угод', 'home.rating': 'оцінка клієнтів', 'home.support': 'підтримка', 'home.experts': 'Експерти NOVA Estate',
});

const initialLocale = typeof window !== 'undefined' && ['en', 'ru', 'uk'].includes(localStorage.getItem('nova_locale') ?? '')
    ? localStorage.getItem('nova_locale') as Locale
    : 'en';
const locale = ref<Locale>(initialLocale);
if (typeof document !== 'undefined') {
    document.documentElement.lang = initialLocale;
}

export function useLocale() {
    const setLocale = (nextLocale: Locale) => {
        locale.value = nextLocale;
        if (typeof window !== 'undefined') {
            localStorage.setItem('nova_locale', nextLocale);
            document.documentElement.lang = nextLocale;
        }
    };
    const t = (key: string) => dictionaries[locale.value][key] ?? dictionaries.en[key] ?? key;
    const localized = (entity: { translations?: LocalizedFields } | null | undefined, field: string, fallback = '') =>
        entity?.translations?.[locale.value]?.[field] ?? entity?.translations?.en?.[field] ?? fallback;

    return { locale: computed(() => locale.value), setLocale, t, localized };
}
