<script setup lang="ts">
import { Head, Link, useForm } from '@inertiajs/vue3';
import AppLayout from '@/Layouts/AppLayout.vue';
import PropertyCard from '@/Components/PropertyCard.vue';
import type { Property, PropertyType, User } from '@/types';
import { useLocale } from '@/composables/useLocale';
defineProps<{ featured: Property[]; types: PropertyType[]; realtors: (User & {properties_count: number})[] }>();
const { localized, t } = useLocale();
const consultation = useForm({ name: '', phone: '', email: '', subject: 'Consultation', message: '' });
const submit = () => consultation.post('/contacts', { preserveScroll: true, onSuccess: () => consultation.reset() });
</script>
<template><Head :title="t('home.title')"/><AppLayout>
    <section class="hero text-white"><div class="container-page flex min-h-[690px] items-center py-20"><div class="max-w-3xl"><div class="eyebrow !text-[#e7cda9]">{{t('home.eyebrow')}}</div><h1 class="mt-5 text-5xl leading-[1.05] md:text-7xl">{{t('home.title')}}</h1><p class="mt-7 max-w-2xl text-lg leading-8 text-stone-200">{{t('home.subtitle')}}</p><form action="/properties" class="mt-10 grid gap-3 rounded-2xl bg-white p-3 text-stone-800 shadow-2xl md:grid-cols-[1fr_180px_auto]"><label><span class="sr-only">{{t('catalog.search')}}</span><input name="search" class="field border-0" :placeholder="t('home.searchPlaceholder')"></label><label><span class="sr-only">{{t('catalog.operation')}}</span><select name="operation" class="field border-0"><option value="sale">{{t('catalog.buy')}}</option><option value="rent">{{t('catalog.rent')}}</option></select></label><button class="btn btn-primary">{{t('home.search')}}</button></form></div></div></section>
    <section class="section"><div class="container-page"><div class="flex items-end justify-between gap-4"><div><div class="eyebrow">{{t('home.featured')}}</div><h2 class="mt-3 text-4xl md:text-5xl">{{t('home.popular')}}</h2></div><Link href="/properties" class="hidden font-bold text-[#174c43] sm:block">{{t('home.all')}} →</Link></div><div class="mt-10 grid gap-7 md:grid-cols-2 lg:grid-cols-3"><PropertyCard v-for="item in featured" :key="item.id" :property="item"/></div></div></section>
    <section class="bg-[#eee9df] py-20"><div class="container-page"><div class="eyebrow">{{t('home.format')}}</div><h2 class="mt-3 text-4xl">{{t('home.formatTitle')}}</h2><div class="mt-9 grid gap-4 sm:grid-cols-2 lg:grid-cols-5"><Link v-for="propertyType in types" :key="propertyType.id" :href="`/properties?type=${propertyType.slug}`" class="card p-6 hover:-translate-y-1"><div class="text-3xl text-[#174c43]">⌂</div><h3 class="mt-5 text-xl">{{ localized(propertyType, 'name', propertyType.name) }}</h3><p class="mt-2 text-sm text-stone-500">{{ propertyType.properties_count }} {{t('home.listings')}}</p></Link></div></div></section>
    <section class="section"><div class="container-page grid gap-12 lg:grid-cols-2"><div><div class="eyebrow">{{t('home.why')}}</div><h2 class="mt-3 text-4xl md:text-5xl">{{t('home.whyTitle')}}</h2><p class="prose-copy mt-6">{{t('home.whyText')}}</p><div class="mt-9 grid grid-cols-2 gap-6"><div><strong class="serif text-4xl text-[#174c43]">12</strong><p class="text-sm text-stone-500">years of expertise</p></div><div><strong class="serif text-4xl text-[#174c43]">980+</strong><p class="text-sm text-stone-500">closed deals</p></div><div><strong class="serif text-4xl text-[#174c43]">4.9</strong><p class="text-sm text-stone-500">client rating</p></div><div><strong class="serif text-4xl text-[#174c43]">24/7</strong><p class="text-sm text-stone-500">support</p></div></div></div><img src="/images/properties/estate-07.jpg" alt="Modern apartment interior" class="h-full min-h-96 w-full rounded-2xl object-cover shadow-xl"></div></section>
    <section class="bg-[#173f38] py-20 text-white"><div class="container-page"><div class="eyebrow !text-[#e7cda9]">{{t('footer.team')}}</div><h2 class="mt-3 text-4xl">NOVA Estate experts</h2><div class="mt-9 grid gap-5 md:grid-cols-3"><article v-for="realtor in realtors" :key="realtor.id" class="rounded-xl border border-white/15 p-7"><div class="grid h-14 w-14 place-items-center rounded-full bg-[#e7cda9] text-xl font-bold text-[#173f38]">{{ realtor.name.charAt(0) }}</div><h3 class="mt-5 text-2xl">{{ realtor.name }}</h3><p class="mt-3 text-sm leading-6 text-stone-300">{{ realtor.bio }}</p><p class="mt-4 text-xs font-bold uppercase tracking-wider text-[#e7cda9]">{{ realtor.properties_count }} {{t('home.listings')}}</p></article></div></div></section>
    <section class="section"><div class="container-page card grid overflow-hidden lg:grid-cols-2"><div class="bg-[#eee9df] p-8 md:p-12"><div class="eyebrow">{{t('home.consultation')}}</div><h2 class="mt-3 text-4xl">{{t('home.consultationTitle')}}</h2><p class="prose-copy mt-5">{{t('home.consultationText')}}</p></div><form class="grid gap-4 p-8 md:p-12" @submit.prevent="submit"><label><span class="label">{{t('home.name')}}</span><input v-model="consultation.name" class="field" required></label><label><span class="label">{{t('home.phone')}}</span><input v-model="consultation.phone" class="field" required></label><label><span class="label">{{t('home.comment')}}</span><textarea v-model="consultation.message" class="field" rows="3"/></label><button class="btn btn-primary" :disabled="consultation.processing">{{t('home.send')}}</button></form></div></section>
</AppLayout></template>
