<script setup lang="ts">
import { Head, Link, router, useForm, usePage } from '@inertiajs/vue3'; import { computed } from 'vue'; import AppLayout from '@/Layouts/AppLayout.vue'; import PropertyCard from '@/Components/PropertyCard.vue'; import type { PageProps, Property } from '@/types';
import { useCurrency } from '@/composables/useCurrency'; import { useLocale } from '@/composables/useLocale';
const props = defineProps<{property: Property; similar: Property[]; isFavorite: boolean}>(); const page = usePage<PageProps>();
const form = useForm({name: page.props.auth.user?.name || '', phone: page.props.auth.user?.phone || '', email: page.props.auth.user?.email || '', message: 'Хочу договориться о просмотре объекта.'});
const { formatPrice } = useCurrency(); const { localized, t } = useLocale();
const title = computed(() => localized(props.property, 'title', props.property.title));
const description = computed(() => localized(props.property, 'description', props.property.description));
const address = computed(() => localized(props.property, 'address', props.property.address));
const district = computed(() => localized(props.property, 'district', props.property.district));
const typeName = computed(() => localized(props.property.type, 'name', props.property.type.name));
const submit = () => form.post(`/applications/${props.property.slug}`, {preserveScroll:true, onSuccess:()=>form.reset('message')});
const favorite = () => page.props.auth.user ? router.visit(`/favorites/${props.property.slug}`,{method:props.isFavorite?'delete':'post',preserveScroll:true}) : router.visit('/login');
const compare = () => { const items:Property[]=JSON.parse(localStorage.getItem('nova_compare')||'[]'); if(!items.some(i=>i.id===props.property.id)){localStorage.setItem('nova_compare',JSON.stringify([...items,props.property].slice(-4)))} router.visit('/compare'); };
</script>
<template><Head :title="title"/><AppLayout><section class="py-8"><div class="container-page"><div class="mb-6 text-sm text-stone-500"><Link href="/properties">{{t('footer.catalog')}}</Link> / {{ title }}</div><div class="grid gap-3 md:grid-cols-2"><img :src="property.images[0]?.path || property.cover_url" :alt="title" class="h-[480px] w-full rounded-2xl object-cover md:row-span-2"><img v-for="image in property.images.slice(1,3)" :src="image.path" :alt="title" class="hidden h-[234px] w-full rounded-2xl object-cover md:block"><div v-if="property.images.length < 2" class="hidden h-[480px] place-items-center rounded-2xl bg-[#e9e3d9] text-[#174c43] md:grid"><span class="serif text-4xl">NOVA Estate</span></div></div></div></section>
<section class="pb-20"><div class="container-page grid gap-12 lg:grid-cols-[1fr_390px]"><div><div class="flex flex-wrap items-center gap-3"><span class="status">{{ property.operation==='sale'?t('property.sale'):t('property.rent') }}</span><span class="text-sm text-stone-500">{{ typeName }} · {{ district }}</span></div><h1 class="mt-4 text-4xl md:text-5xl">{{ title }}</h1><p class="mt-3 text-stone-500">{{ address }}</p><div class="mt-8 grid grid-cols-2 gap-4 border-y py-6 sm:grid-cols-4"><div><small class="text-stone-500">{{t('property.area')}}</small><strong class="block text-xl">{{ property.area }} m²</strong></div><div><small class="text-stone-500">{{t('property.rooms')}}</small><strong class="block text-xl">{{ property.rooms || '—' }}</strong></div><div><small class="text-stone-500">{{t('property.floor')}}</small><strong class="block text-xl">{{ property.floor || '—' }} / {{ property.total_floors || '—' }}</strong></div><div><small class="text-stone-500">{{t('property.district')}}</small><strong class="block text-base">{{ district }}</strong></div></div><h2 class="mt-10 text-3xl">{{t('property.about')}}</h2><p class="prose-copy mt-5 whitespace-pre-line">{{ description }}</p><h2 class="mt-10 text-3xl">{{t('property.amenities')}}</h2><div class="mt-5 flex flex-wrap gap-3"><span v-for="a in property.amenities" :key="a.id" class="rounded-full bg-[#e7eee9] px-4 py-2 text-sm font-bold text-[#174c43]">✓ {{ localized(a, 'name', a.name) }}</span></div><div v-if="property.realtor" class="card mt-10 flex items-center gap-5 p-6"><div class="grid h-16 w-16 place-items-center rounded-full bg-[#e7cda9] text-2xl font-bold text-[#173f38]">{{ property.realtor.name.charAt(0) }}</div><div><small class="text-stone-500">{{t('property.agent')}}</small><h3 class="text-2xl">{{ property.realtor.name }}</h3><p class="mt-1 text-sm text-stone-500">{{ property.realtor.phone }}</p></div></div></div>
<aside><div class="card sticky top-28 p-7"><div class="serif text-4xl font-bold text-[#174c43]">{{ formatPrice(property.price) }}<small v-if="property.operation==='rent'" class="font-sans text-sm font-normal"> / {{t('property.month')}}</small></div><div class="mt-5 grid grid-cols-2 gap-2"><button class="btn btn-light" @click="favorite">{{ isFavorite?`♥ ${t('property.saved')}`:`♡ ${t('property.favorite')}` }}</button><button class="btn btn-light" @click="compare">⇄ {{t('property.compare')}}</button></div><h3 class="mt-8 text-2xl">{{t('property.book')}}</h3><form class="mt-5 grid gap-4" @submit.prevent="submit"><label><span class="label">{{t('property.name')}}</span><input v-model="form.name" class="field" required><span class="text-xs text-red-700">{{ form.errors.name }}</span></label><label><span class="label">{{t('property.phone')}}</span><input v-model="form.phone" class="field" required></label><label><span class="label">{{t('property.message')}}</span><textarea v-model="form.message" class="field" rows="3"/></label><button class="btn btn-primary" :disabled="form.processing">{{t('property.send')}}</button></form></div></aside></div></section>
<section v-if="similar.length" class="bg-[#eee9df] py-20"><div class="container-page"><div class="eyebrow">Похожие предложения</div><h2 class="mt-3 text-4xl">Вам может подойти</h2><div class="mt-9 grid gap-6 md:grid-cols-3"><PropertyCard v-for="item in similar" :property="item"/></div></div></section></AppLayout></template>
