<script setup lang="ts">
import { Head, Link, router, useForm } from '@inertiajs/vue3';
import DashboardLayout from '@/Layouts/DashboardLayout.vue';
import { useLocale } from '@/composables/useLocale';
import type { Property, PropertyType, User } from '@/types';

const props = defineProps<{ property?: Property; types: PropertyType[]; amenities: { id: number; name: string; translations?: Record<string, Record<string, string>> }[]; realtors: User[] }>();
const { t, localized } = useLocale();
const form = useForm({ title: props.property?.title || '', slug: props.property?.slug || '', description: props.property?.description || '', property_type_id: props.property?.type?.id || '', realtor_id: props.property?.realtor?.id || '', operation: props.property?.operation || 'sale', price: props.property?.price || '', address: props.property?.address || '', district: props.property?.district || '', rooms: props.property?.rooms || '', area: props.property?.area || '', floor: props.property?.floor || '', total_floors: props.property?.total_floors || '', status: props.property?.status || 'draft', is_featured: props.property?.is_featured || false, amenities: props.property?.amenities?.map(item => item.id) || [], images: [] as File[] });
const submit = () => { const options = { forceFormData: true }; props.property ? form.post(`/manage/properties/${props.property.slug}`, { ...options, _method: 'patch' } as any) : form.post('/manage/properties', options); };
const files = (event: Event) => form.images = Array.from((event.target as HTMLInputElement).files || []);
const deleteImage = (id: number) => router.delete(`/manage/properties/${props.property?.slug}/images/${id}`, { preserveScroll: true });
</script>
<template>
    <Head :title="t(property ? 'form.editTitle' : 'form.newTitle')" />
    <DashboardLayout>
        <Link href="/manage/properties" class="text-[#174c43]">← {{ t('form.back') }}</Link>
        <h1 class="mt-4 text-4xl">{{ t(property ? 'form.editTitle' : 'form.newTitle') }}</h1>
        <form class="mt-8 grid gap-6" @submit.prevent="submit">
            <section class="card grid gap-5 p-7"><h2 class="text-2xl">{{ t('form.basic') }}</h2><label><span class="label">{{ t('form.title') }}</span><input v-model="form.title" class="field" required><span class="text-xs text-red-700">{{ form.errors.title }}</span></label><label><span class="label">{{ t('form.description') }}</span><textarea v-model="form.description" class="field" rows="7" required /><span class="text-xs text-red-700">{{ form.errors.description }}</span></label><div class="grid gap-4 md:grid-cols-3"><label><span class="label">{{ t('catalog.type') }}</span><select v-model="form.property_type_id" class="field" required><option value="" disabled>{{ t('form.select') }}</option><option v-for="type in types" :key="type.id" :value="type.id">{{ localized(type, 'name', type.name) }}</option></select></label><label><span class="label">{{ t('catalog.operation') }}</span><select v-model="form.operation" class="field"><option value="sale">{{ t('property.sale') }}</option><option value="rent">{{ t('property.rent') }}</option></select></label><label><span class="label">{{ t('form.price') }}</span><input v-model="form.price" class="field" type="number" min="1" required></label></div></section>
            <section class="card grid gap-5 p-7"><h2 class="text-2xl">{{ t('form.location') }}</h2><div class="grid gap-4 md:grid-cols-2"><label><span class="label">{{ t('form.address') }}</span><input v-model="form.address" class="field" required></label><label><span class="label">{{ t('property.district') }}</span><input v-model="form.district" class="field" required></label></div><div class="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><label><span class="label">{{ t('property.rooms') }}</span><input v-model="form.rooms" class="field" type="number"></label><label><span class="label">{{ t('property.area') }}, m²</span><input v-model="form.area" class="field" type="number" step="0.1" required></label><label><span class="label">{{ t('property.floor') }}</span><input v-model="form.floor" class="field" type="number"></label><label><span class="label">{{ t('form.totalFloors') }}</span><input v-model="form.total_floors" class="field" type="number"></label></div></section>
            <section class="card p-7"><h2 class="text-2xl">{{ t('property.amenities') }}</h2><div class="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><label v-for="amenity in amenities" :key="amenity.id" class="flex items-center gap-2 text-sm"><input v-model="form.amenities" type="checkbox" :value="amenity.id" class="rounded border-stone-300 text-[#174c43]">{{ localized(amenity, 'name', amenity.name) }}</label></div></section>
            <section class="card grid gap-5 p-7"><h2 class="text-2xl">{{ t('form.publication') }}</h2><div class="grid gap-4 md:grid-cols-2"><label><span class="label">{{ t('manage.status') }}</span><select v-model="form.status" class="field"><option v-for="status in ['draft', 'moderation', 'published', 'sold', 'rented']" :key="status" :value="status">{{ t(`manage.${status}`) }}</option></select></label><label v-if="realtors.length"><span class="label">{{ t('property.agent') }}</span><select v-model="form.realtor_id" class="field"><option value="">{{ t('manage.unassigned') }}</option><option v-for="realtor in realtors" :key="realtor.id" :value="realtor.id">{{ realtor.name }}</option></select></label></div><label class="flex items-center gap-2"><input v-model="form.is_featured" type="checkbox">{{ t('form.featured') }}</label><label><span class="label">{{ t('form.addPhotos') }}</span><input class="field" type="file" multiple accept="image/*" @change="files"></label><div v-if="property?.images?.length" class="grid grid-cols-2 gap-3 md:grid-cols-4"><div v-for="image in property.images" :key="image.id" class="relative"><img :src="image.path" :alt="image.alt" class="h-32 w-full rounded-lg object-cover"><button type="button" class="absolute right-2 top-2 rounded bg-white px-2 py-1 text-xs font-bold text-red-700" @click="deleteImage(image.id)">{{ t('manage.delete') }}</button></div></div></section>
            <div class="flex gap-3"><button class="btn btn-primary" :disabled="form.processing">{{ t(property ? 'form.save' : 'form.create') }}</button><Link href="/manage/properties" class="btn btn-light">{{ t('profile.cancel') }}</Link></div>
        </form>
    </DashboardLayout>
</template>
